### PR TITLE
fix grammar of hit message

### PR DESCRIPTION
**Pull request by djuretic**
There were messages like this: "Hobgoblin hit the you for 6 damage!"
I removed the extra "the" when you get attacked.

### CODE REVIEW

**Comment by mordrax** [comment]
While you're here, could you also fix the case of when a monster is the attacker, it should say "_The_ hobgoblin hit you..." instead of "Hobgoblin hit you..."

Looks like it's a matter of putting "The" and lowercasing the monster name here:
https://github.com/djuretic/cotwelm/blob/772ee382fdfb21f3d7bf87047aef6f932a310b6f/src/Game/Collision.elm#L148

**Comment by djuretic** [comment]
Done adding the extra 'The'.

About lowercasing the monster name, in the case of bosses (e.g. Hrugnir) it won't work very well (it is a proper noun). To keep it simple I'll suggest not to change the case of the mosters' name.

**Comment by mordrax** [comment]
That's a good point, let's see how it looks as is with capitalised monster names.

**Comment by djuretic** [comment]
Just look at the original game, it capitalized every monster name.

**Pull request merged**
